### PR TITLE
59 testing user service test briiite

### LINKED ISSUE #59: [Testing] User Service Test
### Resources: 
Resource from Azhya: 
[Spring Boot Testing Basics: How to Unit Test & Integration Test REST Controllers](https://www.youtube.com/watch?v=pNiRNRgi5Ws)

Additional Resources:
[Test Driven Development with Spring Boot - Sannidhi Jalukar, Madhura Bhave](https://www.youtube.com/watch?v=s9vt6UJiHg4)

-----
### Methods: 
As a small reminder, we only need the minimum amount of controller code needed to actually run the test (Calvin's example should show that). 
Note: It's expected to fail. 
Action item: Please go ahead and set up the minimum amount of code (in the Controller layer) for your assigned testing table that you will need to create your test. 

Your tests should have the following methods: 
- getAll
- getById
- Create
- Update
- Delete

### PR DESCRIPTION
**Pull request by briiitelord**
Added methods:

- login
- deleteUserById

All service tests with complete implementation passed

### CODE REVIEW

**Review by pyaeger — APPROVED** [review]
Thanks for the work! Note that GitHub is flagging a conflict that needs to be resolved. Adding my approval pending the conflict resolution and Calvin's review.

**Comment by FullSol** [comment]
@pyaeger resolutions are your (and my) job.
This is selecting what code will be pushed into the dev branch.

**Comment by pyaeger** [comment]
@FullSol My apologies. I realize now that I do not understand enough to be an effective Gitflow Master. Please remove me from the role.

**Review by FullSol — APPROVED** [review]
Looks good. made some edits on some decisions made today about naming conventions.

**Pull request merged**
