### PR TITLE
Instructions for Branching

### LINKED ISSUE #1: [DOC] Instructions for Git Branching

### PR DESCRIPTION
**Pull request by L3viathon**

### CODE REVIEW

**Comment by L3viathon** [comment]
UNFINISHED. Testing things out:)

**Comment by L3viathon** [comment]
closes #1

**Review by FullSol — APPROVED** [review]
Reviewed, understand, and agree.

**Comment by jularmerme** [comment]
Reviewed

**Review by jularmerme — APPROVED** [review]
Reviewed

**Review by briiitelord — APPROVED** [review]
Approved

**Review by pyaeger — APPROVED** [review]
Looks good. Onward!

**Comment by pyaeger** [comment]
Closes #1

**Pull request merged**
