### PR TITLE
added er diagram example

### LINKED ISSUE #18: [DEV] Create ERS Diagram

### PR DESCRIPTION
**Pull request by FullSol**

### CODE REVIEW

**Comment by FullSol** [comment]
closes #18

**Review by pyaeger — APPROVED** [review]
Looks good. Well organized.

**Comment by pyaeger** [comment]
@FullSol There is a GitHub message noting "Merging can be performed automatically".. Does that mean I don't need to manually merge this pull request as it will happen based on the trigger you created from issue #18? Or shall I go ahead and merge the pull request then delete the branch if given that option?

**Review by L3viathon — APPROVED** [review]
@FullSol Thank you for creating this. I'll update the Sprint.md file to match.

**Pull request merged**
